// <auto-generated />
using System;
using EGI_Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGI_Backend.Infrastructure.Migrations
{
    [DbContext(typeof(EGIDbContext))]
    [Migration("20260314161347_ClaimFraudEngine")]
    partial class ClaimFraudEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AgentCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorporateClientId");

                    b.ToTable("AgentCustomers");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AdminApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AdminApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClaimType")
                        .HasColumnType("int");

                    b.Property<Guid?>("DependentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExtractedBillAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExtractedBillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedCauseOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExtractedDateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedFirNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedHospitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExtractedIncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedPoliceStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FraudAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FraudScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAutoApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspectedFraud")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresAdminApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminApprovedByUserId");

                    b.HasIndex("ClaimDate");

                    b.HasIndex("DependentId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("Status");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BusinessCategory")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReSubmissionCount")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CorporateClients");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClientDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CorporateClientId");

                    b.ToTable("CorporateClientDocuments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.InsurancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("InsurancePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BasePremium = 2000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7746),
                            Description = "Health: ₹2L | Covers: Employee Only | No Life | No Accident",
                            PlanCode = "S-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            BasePremium = 4000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7774),
                            Description = "Health: ₹3L | Covers: Employee + Spouse + 2 Children | No Life | No Accident",
                            PlanCode = "S-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            BasePremium = 6000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7780),
                            Description = "Health: ₹3L (Family) | Life: ₹5L | No Accident | Parents Not Included",
                            PlanCode = "S-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            BasePremium = 2500m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7797),
                            Description = "Health: ₹3L | Covers: Employee Only",
                            PlanCode = "M-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BasePremium = 5000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7802),
                            Description = "Health: ₹5L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "M-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            BasePremium = 8000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7807),
                            Description = "Health: ₹5L (Family) | Life: ₹10L | Parents Not Included",
                            PlanCode = "M-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            BasePremium = 10000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7811),
                            Description = "Health: ₹7L (Family) | Life: ₹15L | Accident: ₹10L | Parents Optional Add-on",
                            PlanCode = "M-Level 4",
                            PlanName = "Health + Life + Accident",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            BasePremium = 4000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7815),
                            Description = "Health: ₹5L | Covers: Employee Only",
                            PlanCode = "L-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            BasePremium = 7000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7820),
                            Description = "Health: ₹7L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "L-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BasePremium = 12000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7825),
                            Description = "Health: ₹7L (Family) | Life: ₹20L",
                            PlanCode = "L-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            BasePremium = 16000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7828),
                            Description = "Health: ₹10L (Family) | Life: ₹30L | Accident: ₹20L",
                            PlanCode = "L-Level 4",
                            PlanName = "Health + Life + Accident",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            BasePremium = 25000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7836),
                            Description = "Health: ₹15L (Employee + Spouse + 2 Children + Parents) | Life: ₹40L | Accident: ₹30L | Critical Illness Included",
                            PlanCode = "L-Level 5",
                            PlanName = "Comprehensive Plus",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            BasePremium = 6000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7840),
                            Description = "Health: ₹7L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "E-Level 1",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            BasePremium = 14000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7844),
                            Description = "Health: ₹10L (Employee + Spouse + 2 Children) | Life: ₹30L",
                            PlanCode = "E-Level 2",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            BasePremium = 30000m,
                            CreatedAt = new DateTime(2026, 3, 14, 16, 13, 45, 735, DateTimeKind.Utc).AddTicks(7848),
                            Description = "Health: ₹20L (Employee + Spouse + 2 Children + Parents) | Life: ₹50L | Accident: ₹40L | Global Coverage Option | Dedicated Claim Officer",
                            PlanCode = "E-Level 3",
                            PlanName = "Full Corporate Shield",
                            Status = true
                        });
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillingPeriodFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BillingPeriodTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CommissionEarned")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPenaltyApplied")
                        .HasColumnType("bit");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("Status");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CorporateClientId");

                    b.HasIndex("PolicyAssignmentId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaidBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaidBy");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PlanCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CoverageAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CoveredGroup")
                        .HasColumnType("int");

                    b.Property<Guid>("InsurancePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePlanId");

                    b.ToTable("PlanCoverages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82e1ef72-35cd-475a-879b-dd2753eff603"),
                            CoverageAmount = 200000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("cbe85e32-95eb-4e4b-94fd-6e8c36dd6034"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111112"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("9ca5cfa0-90c1-4519-85b9-5c47219876d5"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111113"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("946b6110-ea65-4ff3-a082-ede83a3ae9f7"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111113"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("dbd458be-a7a4-4810-a2ad-962f48f10b8c"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222221"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("c83b673c-406b-49b7-a1e8-4e83512e3986"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("2c6b1447-8fba-4994-9523-62f43d07a818"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222223"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("7f8e44af-1544-478d-a4ae-401cecac5e98"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222223"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("047d5c1d-0cbb-482a-a8f1-c0a5d2b93b85"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d4f4b733-ff51-426f-9958-390b37de8c17"),
                            CoverageAmount = 1500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f8d6c249-6282-4af1-a811-7b0fb90727e8"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("865267b4-617a-44a7-ac9b-2022773755ad"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333331"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e160b165-9a4a-438b-a5ba-8f2f12b2379e"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333332"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ad620ca8-9880-4aea-b351-bde69cab3a3c"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("5ff7418c-34d1-46c2-8213-a20ce488e2aa"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("e26b182f-be75-4b1e-9c5d-0b517e5972e7"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("54575124-5f10-4fd0-9487-8100499165b6"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("b74190e6-549a-4faf-9d75-8332ed36f373"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("5497c171-ef93-4fc0-a000-f4addb9d87a9"),
                            CoverageAmount = 1500000m,
                            CoveredGroup = 2,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("4e381bab-d66b-4e18-9c30-22433ee338a3"),
                            CoverageAmount = 4000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("951d8c60-e82d-4ea6-97a9-211a2eec0ec5"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("37f66b1c-0c08-47ab-a1f7-dd2a2299a340"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("fbccc46c-6920-46b1-96a1-e74fe2774d4c"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444441"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("60b312e1-ce77-4958-a2d4-687e40e67ec3"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444442"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ae2fdc95-f2bd-4626-b666-e5bf2cc5cb97"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444442"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c1c6ec37-d1ac-4e1b-981c-bdf6f4d38ca2"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 2,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("adceae39-1b6d-45ad-b087-b7b9c0087069"),
                            CoverageAmount = 5000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("cbf0a18f-5951-4d5c-916b-ce5bd49265e4"),
                            CoverageAmount = 4000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 2
                        });
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillingFrequency")
                        .HasColumnType("int");

                    b.Property<int>("BusinessCategory")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsurancePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorporateClientId");

                    b.HasIndex("InsurancePlanId");

                    b.HasIndex("Status");

                    b.ToTable("PolicyAssignments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyEndorsement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CommissionAdjustment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndorsementData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PremiumAdjustment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("PolicyEndorsements");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AgentCustomer", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CorporateClient");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "AdminApprovedByUser")
                        .WithMany()
                        .HasForeignKey("AdminApprovedByUserId");

                    b.HasOne("EGI_Backend.Domain.Entities.Dependent", "Dependent")
                        .WithMany()
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EGI_Backend.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdminApprovedByUser");

                    b.Navigation("Dependent");

                    b.Navigation("Member");

                    b.Navigation("PolicyAssignment");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClaimDocument", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("EGI_Backend.Domain.Entities.CorporateClient", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClientDocument", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", null)
                        .WithMany("Documents")
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Dependent", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Member", "Member")
                        .WithMany("Dependents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany("Members")
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorporateClient");

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Payment", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "PaidByUser")
                        .WithMany()
                        .HasForeignKey("PaidBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PaidByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PlanCoverage", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.InsurancePlan", "InsurancePlan")
                        .WithMany("Coverages")
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CorporateClient");

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyEndorsement", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PolicyAssignment");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.InsurancePlan", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.Navigation("Dependents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
