// <auto-generated />
using System;
using EGI_Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGI_Backend.Infrastructure.Migrations
{
    [DbContext(typeof(EGIDbContext))]
    [Migration("20260305103600_AddCommissionToInvoice")]
    partial class AddCommissionToInvoice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AgentCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorporateClientId");

                    b.ToTable("AgentCustomers");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClaimType")
                        .HasColumnType("int");

                    b.Property<Guid?>("DependentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DependentId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BusinessCategory")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReSubmissionCount")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CorporateClients");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClientDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CorporateClientId");

                    b.ToTable("CorporateClientDocuments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.InsurancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("InsurancePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BasePremium = 2000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6279),
                            Description = "Health: ?2L | Covers: Employee Only | No Life | No Accident",
                            PlanCode = "S-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            BasePremium = 4000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6310),
                            Description = "Health: ?3L | Covers: Employee + Spouse + 2 Children | No Life | No Accident",
                            PlanCode = "S-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            BasePremium = 6000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6318),
                            Description = "Health: ?3L (Family) | Life: ?5L | No Accident | Parents Not Included",
                            PlanCode = "S-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            BasePremium = 2500m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6325),
                            Description = "Health: ?3L | Covers: Employee Only",
                            PlanCode = "M-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BasePremium = 5000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6332),
                            Description = "Health: ?5L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "M-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            BasePremium = 8000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6352),
                            Description = "Health: ?5L (Family) | Life: ?10L | Parents Not Included",
                            PlanCode = "M-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            BasePremium = 10000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6359),
                            Description = "Health: ?7L (Family) | Life: ?15L | Accident: ?10L | Parents Optional Add-on",
                            PlanCode = "M-Level 4",
                            PlanName = "Health + Life + Accident",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            BasePremium = 4000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6365),
                            Description = "Health: ?5L | Covers: Employee Only",
                            PlanCode = "L-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            BasePremium = 7000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6371),
                            Description = "Health: ?7L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "L-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BasePremium = 12000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6377),
                            Description = "Health: ?7L (Family) | Life: ?20L",
                            PlanCode = "L-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            BasePremium = 16000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6383),
                            Description = "Health: ?10L (Family) | Life: ?30L | Accident: ?20L",
                            PlanCode = "L-Level 4",
                            PlanName = "Health + Life + Accident",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            BasePremium = 25000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6388),
                            Description = "Health: ?15L (Employee + Spouse + 2 Children + Parents) | Life: ?40L | Accident: ?30L | Critical Illness Included",
                            PlanCode = "L-Level 5",
                            PlanName = "Comprehensive Plus",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            BasePremium = 6000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6394),
                            Description = "Health: ?7L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "E-Level 1",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            BasePremium = 14000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6406),
                            Description = "Health: ?10L (Employee + Spouse + 2 Children) | Life: ?30L",
                            PlanCode = "E-Level 2",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            BasePremium = 30000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 35, 58, 280, DateTimeKind.Utc).AddTicks(6412),
                            Description = "Health: ?20L (Employee + Spouse + 2 Children + Parents) | Life: ?50L | Accident: ?40L | Global Coverage Option | Dedicated Claim Officer",
                            PlanCode = "E-Level 3",
                            PlanName = "Full Corporate Shield",
                            Status = true
                        });
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillingPeriodFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BillingPeriodTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CommissionEarned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyAssignmentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyAssignmentId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaidBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaidBy");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PlanCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CoverageAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CoveredGroup")
                        .HasColumnType("int");

                    b.Property<Guid>("InsurancePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePlanId");

                    b.ToTable("PlanCoverages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc1c21d8-5938-4139-a7cf-baa19da13841"),
                            CoverageAmount = 200000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("eb27d94d-78b1-4099-b61a-4895db603bb7"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111112"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("408c5653-1b76-4267-ac5c-a8402df1abed"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111113"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("8f39f9e0-b52e-435b-9415-7b0f97016b29"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111113"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("85d30900-74af-4453-815a-72af9382a037"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222221"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("b028de87-89d8-46c0-926e-853f07e872cc"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("7c3b877e-7899-4200-a08e-cec9dc607cff"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222223"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("948f8e1a-c490-448e-826f-e909f0199ef6"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222223"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("caf4f144-db8b-4d34-8655-7f633ff64a29"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("831955fe-f02d-4420-a5a9-33788bc6409b"),
                            CoverageAmount = 1500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("0fc06b76-41a4-4673-8393-ef3f50f04172"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("00a18bf0-ee32-4050-a90d-622088e1856a"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333331"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("11945faa-04b0-45b2-85dd-130ce5c9015c"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333332"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("5806b1d8-551c-4dd3-a7cf-33f01c3d5a3a"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("cf422279-ffdc-457e-96a7-a765b8b88b9f"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("dcb51727-fb00-47a9-9564-9a12e123ca1f"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("852ee4d9-c681-4fb5-91ce-eb8202dbcaa2"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("2e867e60-73a4-4d1d-be20-610c521d4b1a"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("cd35812c-486e-4437-8bc8-769514e40213"),
                            CoverageAmount = 1500000m,
                            CoveredGroup = 2,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("00edeba1-89b6-499f-98aa-fee747432a88"),
                            CoverageAmount = 4000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("75e87ec9-4778-4e04-9519-d2129fcbcded"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("0d51d8d6-924f-4223-8d70-0894020bc938"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("15eecf30-11dd-4874-b777-cd717c507bbb"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444441"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("3a69f111-36aa-4821-bc8c-83a224f4862b"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444442"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e7f67693-4dba-49f5-b111-4574af09070c"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444442"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("dcf28fe1-7f7c-492b-8fad-0e09ef85d97b"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 2,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("2a3dd9cf-69f4-4f29-b4ea-f2da06f271c0"),
                            CoverageAmount = 5000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c6f9507d-97cc-44ad-8d67-4ea5c2054aab"),
                            CoverageAmount = 4000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 2
                        });
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillingFrequency")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsurancePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorporateClientId");

                    b.HasIndex("InsurancePlanId");

                    b.ToTable("PolicyAssignments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyEndorsement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndorsementData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PremiumAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("PolicyEndorsements");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AgentCustomer", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CorporateClient");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Dependent", "Dependent")
                        .WithMany()
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EGI_Backend.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dependent");

                    b.Navigation("Member");

                    b.Navigation("PolicyAssignment");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClaimDocument", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("EGI_Backend.Domain.Entities.CorporateClient", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClientDocument", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", null)
                        .WithMany("Documents")
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Dependent", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Member", "Member")
                        .WithMany("Dependents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany("Members")
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Payment", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "PaidByUser")
                        .WithMany()
                        .HasForeignKey("PaidBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PaidByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PlanCoverage", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.InsurancePlan", "InsurancePlan")
                        .WithMany("Coverages")
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CorporateClient");

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyEndorsement", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PolicyAssignment");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.InsurancePlan", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.Navigation("Dependents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
