// <auto-generated />
using System;
using EGI_Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGI_Backend.Infrastructure.Migrations
{
    [DbContext(typeof(EGIDbContext))]
    [Migration("20260321195443_ClinicDispatch")]
    partial class ClinicDispatch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AgentCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorporateClientId");

                    b.ToTable("AgentCustomers");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AIAdjudicationReasoning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AIConfidenceScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AdminApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AdminApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaimReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClaimType")
                        .HasColumnType("int");

                    b.Property<Guid?>("DependentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ExtractedBillAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExtractedBillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedCauseOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExtractedDateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedDiagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedFirNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractedHospitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExtractedIncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedPoliceStation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FraudAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FraudOverriddenBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FraudOverrideReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FraudScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAIApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutoApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCashless")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFraudOverridden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSettledWithHospital")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuspectedFraud")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NetworkHospitalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresAdminApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdminApprovedByUserId");

                    b.HasIndex("ClaimDate");

                    b.HasIndex("ClaimNumber")
                        .IsUnique();

                    b.HasIndex("DependentId");

                    b.HasIndex("MemberId");

                    b.HasIndex("NetworkHospitalId");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("Status");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClinicalDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverageSummaryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DependentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DispatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HospitalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DependentId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("MemberId");

                    b.ToTable("ClinicalDispatches");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BusinessCategory")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IndustryType")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("KybAiAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KybAiConfidenceScore")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReSubmissionCount")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CorporateClients");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClientDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CorporateClientId");

                    b.ToTable("CorporateClientDocuments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Hospital", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNetworkHospital")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Specialties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("IsNetworkHospital");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.InsurancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("InsurancePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BasePremium = 2000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(260),
                            Description = "Health: ₹2L | Covers: Employee Only | No Life | No Accident",
                            PlanCode = "S-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            BasePremium = 4000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(288),
                            Description = "Health: ₹3L | Covers: Employee + Spouse + 2 Children | No Life | No Accident",
                            PlanCode = "S-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            BasePremium = 6000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(304),
                            Description = "Health: ₹3L (Family) | Life: ₹5L | No Accident | Parents Not Included",
                            PlanCode = "S-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            BasePremium = 2500m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(310),
                            Description = "Health: ₹3L | Covers: Employee Only",
                            PlanCode = "M-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BasePremium = 5000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(314),
                            Description = "Health: ₹5L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "M-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            BasePremium = 8000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(317),
                            Description = "Health: ₹5L (Family) | Life: ₹10L | Parents Not Included",
                            PlanCode = "M-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            BasePremium = 10000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(324),
                            Description = "Health: ₹7L (Family) | Life: ₹15L | Accident: ₹10L | Parents Optional Add-on",
                            PlanCode = "M-Level 4",
                            PlanName = "Health + Life + Accident",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            BasePremium = 4000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(327),
                            Description = "Health: ₹5L | Covers: Employee Only",
                            PlanCode = "L-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            BasePremium = 7000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(332),
                            Description = "Health: ₹7L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "L-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BasePremium = 12000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(335),
                            Description = "Health: ₹7L (Family) | Life: ₹20L",
                            PlanCode = "L-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            BasePremium = 16000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(343),
                            Description = "Health: ₹10L (Family) | Life: ₹30L | Accident: ₹20L",
                            PlanCode = "L-Level 4",
                            PlanName = "Health + Life + Accident",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            BasePremium = 25000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(357),
                            Description = "Health: ₹15L (Employee + Spouse + 2 Children + Parents) | Life: ₹40L | Accident: ₹30L | Critical Illness Included",
                            PlanCode = "L-Level 5",
                            PlanName = "Comprehensive Plus",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            BasePremium = 6000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(360),
                            Description = "Health: ₹7L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "E-Level 1",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            BasePremium = 14000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(364),
                            Description = "Health: ₹10L (Employee + Spouse + 2 Children) | Life: ₹30L",
                            PlanCode = "E-Level 2",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            BasePremium = 30000m,
                            CreatedAt = new DateTime(2026, 3, 21, 19, 54, 40, 278, DateTimeKind.Utc).AddTicks(367),
                            Description = "Health: ₹20L (Employee + Spouse + 2 Children + Parents) | Life: ₹50L | Accident: ₹40L | Global Coverage Option | Dedicated Claim Officer",
                            PlanCode = "E-Level 3",
                            PlanName = "Full Corporate Shield",
                            Status = true
                        });
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillingPeriodFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BillingPeriodTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CommissionEarned")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsPenaltyApplied")
                        .HasColumnType("bit");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("InvoiceNo")
                        .IsUnique();

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("Status");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastClaimAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CorporateClientId");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("EmployeeCode", "CorporateClientId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaidBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaidBy");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PlanCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CoverageAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CoveredGroup")
                        .HasColumnType("int");

                    b.Property<Guid>("InsurancePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePlanId");

                    b.ToTable("PlanCoverages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59ef49d8-be66-44c3-85de-f55437555b1b"),
                            CoverageAmount = 200000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("42b457d9-8d49-4d54-b1b8-93b21b878d4d"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111112"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("22eed64e-c84d-485d-8cc2-0ef8f0319873"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111113"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("f41f9662-bd8e-4193-9a89-116401e4df62"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111113"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("7da248d1-ed0a-4169-a794-2c2ef216fc46"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222221"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("31a83a4d-0047-435e-8cfa-cecd3090e0b5"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a387be4d-838e-451d-925b-87db8cc7c738"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222223"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("aff10fee-bec0-4007-bb56-ec7a9a543109"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222223"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("852f7fcf-a6bb-4fb2-a773-0070413707c7"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("e8493f1c-b473-49b7-aebe-e0321eb4dd86"),
                            CoverageAmount = 1500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("65332b66-9c95-461a-8367-b46fce295f74"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("cbddd181-bb70-460f-8959-5447b503c2f7"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333331"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("65e0d02f-2c73-4e7e-b13e-539ce2735957"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333332"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("3172ca3f-fd1c-4ac2-9b81-3deb7182f7f1"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("0cab22ea-3c6a-4337-8faf-929a7fbc0e7c"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1257a537-e2b9-485c-bd2f-16d0bbc99c67"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("316b41cd-182c-44b8-9006-5919fc575596"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f68bd1e7-2aec-4d6d-9f9a-fe28485cb9af"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("edc783c2-2258-4d39-8cfa-702966f0150c"),
                            CoverageAmount = 1500000m,
                            CoveredGroup = 2,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("623d5230-8178-4e64-bfd2-d4a9a759e0c8"),
                            CoverageAmount = 4000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("3976e5c8-66d5-4236-8967-ffdc5a6b3dec"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("8371af0a-b42c-4242-abfd-bd342f7cbb2e"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("0f2287cc-0aa3-49f2-b490-4f9ecdf6a0e2"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444441"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("6ef2221c-200a-406f-ad7c-fe8a5d8a7e13"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444442"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("cd0fbdb6-6ac6-4b9e-a9dd-45001060fb63"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444442"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("af5c69a6-ee94-4dfd-adb7-68809717eaba"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 2,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("31366672-12d2-4b4d-82b7-db421f7927a1"),
                            CoverageAmount = 5000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c6545531-076a-486b-b4d6-a2cf8aaa5804"),
                            CoverageAmount = 4000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 2
                        });
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillingFrequency")
                        .HasColumnType("int");

                    b.Property<int>("BusinessCategory")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsurancePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PendingCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PolicyNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorporateClientId");

                    b.HasIndex("InsurancePlanId");

                    b.HasIndex("PolicyNo")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("PolicyAssignments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyEndorsement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CommissionAdjustment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndorsementData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PremiumAdjustment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("PolicyEndorsements");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalaryLPA")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AgentCustomer", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CorporateClient");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "AdminApprovedByUser")
                        .WithMany()
                        .HasForeignKey("AdminApprovedByUserId");

                    b.HasOne("EGI_Backend.Domain.Entities.Dependent", "Dependent")
                        .WithMany()
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EGI_Backend.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.Hospital", "NetworkHospital")
                        .WithMany()
                        .HasForeignKey("NetworkHospitalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AdminApprovedByUser");

                    b.Navigation("Dependent");

                    b.Navigation("Member");

                    b.Navigation("NetworkHospital");

                    b.Navigation("PolicyAssignment");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClaimDocument", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClinicalDispatch", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Dependent", "Dependent")
                        .WithMany()
                        .HasForeignKey("DependentId");

                    b.HasOne("EGI_Backend.Domain.Entities.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependent");

                    b.Navigation("Hospital");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("EGI_Backend.Domain.Entities.CorporateClient", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClientDocument", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany("Documents")
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CorporateClient");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Dependent", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Member", "Member")
                        .WithMany("Dependents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany("Members")
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorporateClient");

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Payment", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "PaidByUser")
                        .WithMany()
                        .HasForeignKey("PaidBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PaidByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PlanCoverage", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.InsurancePlan", "InsurancePlan")
                        .WithMany("Coverages")
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CorporateClient");

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyEndorsement", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PolicyAssignment");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.InsurancePlan", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.Navigation("Dependents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
