// <auto-generated />
using System;
using EGI_Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGI_Backend.Infrastructure.Migrations
{
    [DbContext(typeof(EGIDbContext))]
    [Migration("20260305104537_SetInvoiceDecimalPrecision")]
    partial class SetInvoiceDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AgentCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorporateClientId");

                    b.ToTable("AgentCustomers");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedColumns")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClaimType")
                        .HasColumnType("int");

                    b.Property<Guid?>("DependentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DependentId");

                    b.HasIndex("MemberId");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimDocuments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BusinessCategory")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReSubmissionCount")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReviewedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CorporateClients");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClientDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CorporateClientId");

                    b.ToTable("CorporateClientDocuments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Dependent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Dependents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.InsurancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("InsurancePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BasePremium = 2000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3790),
                            Description = "Health: ?2L | Covers: Employee Only | No Life | No Accident",
                            PlanCode = "S-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            BasePremium = 4000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3806),
                            Description = "Health: ?3L | Covers: Employee + Spouse + 2 Children | No Life | No Accident",
                            PlanCode = "S-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            BasePremium = 6000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3811),
                            Description = "Health: ?3L (Family) | Life: ?5L | No Accident | Parents Not Included",
                            PlanCode = "S-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            BasePremium = 2500m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3815),
                            Description = "Health: ?3L | Covers: Employee Only",
                            PlanCode = "M-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BasePremium = 5000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3819),
                            Description = "Health: ?5L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "M-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            BasePremium = 8000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3822),
                            Description = "Health: ?5L (Family) | Life: ?10L | Parents Not Included",
                            PlanCode = "M-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            BasePremium = 10000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3825),
                            Description = "Health: ?7L (Family) | Life: ?15L | Accident: ?10L | Parents Optional Add-on",
                            PlanCode = "M-Level 4",
                            PlanName = "Health + Life + Accident",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            BasePremium = 4000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3838),
                            Description = "Health: ?5L | Covers: Employee Only",
                            PlanCode = "L-Level 1",
                            PlanName = "Health Basic",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            BasePremium = 7000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3841),
                            Description = "Health: ?7L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "L-Level 2",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BasePremium = 12000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3844),
                            Description = "Health: ?7L (Family) | Life: ?20L",
                            PlanCode = "L-Level 3",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            BasePremium = 16000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3848),
                            Description = "Health: ?10L (Family) | Life: ?30L | Accident: ?20L",
                            PlanCode = "L-Level 4",
                            PlanName = "Health + Life + Accident",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            BasePremium = 25000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3851),
                            Description = "Health: ?15L (Employee + Spouse + 2 Children + Parents) | Life: ?40L | Accident: ?30L | Critical Illness Included",
                            PlanCode = "L-Level 5",
                            PlanName = "Comprehensive Plus",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            BasePremium = 6000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3854),
                            Description = "Health: ?7L | Covers: Employee + Spouse + 2 Children",
                            PlanCode = "E-Level 1",
                            PlanName = "Health Family",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            BasePremium = 14000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3857),
                            Description = "Health: ?10L (Employee + Spouse + 2 Children) | Life: ?30L",
                            PlanCode = "E-Level 2",
                            PlanName = "Health + Life",
                            Status = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            BasePremium = 30000m,
                            CreatedAt = new DateTime(2026, 3, 5, 10, 45, 35, 698, DateTimeKind.Utc).AddTicks(3860),
                            Description = "Health: ?20L (Employee + Spouse + 2 Children + Parents) | Life: ?50L | Accident: ?40L | Global Coverage Option | Dedicated Claim Officer",
                            PlanCode = "E-Level 3",
                            PlanName = "Full Corporate Shield",
                            Status = true
                        });
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BillingPeriodFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BillingPeriodTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CommissionEarned")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyAssignmentId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("SumInsured")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PolicyAssignmentId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PaidBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaidBy");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PlanCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CoverageAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CoveredGroup")
                        .HasColumnType("int");

                    b.Property<Guid>("InsurancePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsurancePlanId");

                    b.ToTable("PlanCoverages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42ca29ae-6a97-4aed-94ab-0c4e9139b65b"),
                            CoverageAmount = 200000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("710ccd3a-9727-498c-80eb-5be04e064cac"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111112"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("2a764c81-a5dd-4a08-bea3-de1bd08a5d63"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111113"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("342200e3-45db-44e7-9974-a933112eaf38"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("11111111-1111-1111-1111-111111111113"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("9d9147f8-8c86-407f-b2e8-7b3aab27ebdb"),
                            CoverageAmount = 300000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222221"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("a2ac23c7-6571-4896-9513-8fc75359751c"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("8129c26e-217f-4c9c-abb4-302a22722504"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222223"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("24c75336-6a13-47f2-bf31-3665a899afb7"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222223"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("5b38aaa7-8662-4542-ba19-d1f4c47df48e"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("4c876dc6-a0bc-4aac-b5f5-18549eb9a116"),
                            CoverageAmount = 1500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("4a0d1872-9524-46a2-91d7-fdff431eb8e9"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("22222222-2222-2222-2222-222222222224"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("31f0f194-6138-4cd0-9573-79798957baab"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333331"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d2f357e1-b2ad-4516-84e1-f3797e8c6ced"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333332"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("75d90d9b-99b1-4cde-bfce-2eecc7bc5592"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("bab685c0-604f-485a-bc90-0e18a52cbc91"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("fbc4982d-47f8-4eae-a856-9f1593e61dd0"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("7247780c-f84d-4d59-b748-b56981752a18"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a769d4e5-f882-4792-a075-4ebfd7215545"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333334"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("f1cd9fb7-d173-43c3-bf10-c7535692a178"),
                            CoverageAmount = 1500000m,
                            CoveredGroup = 2,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("3614ab07-9bda-44f4-bc4d-64d9bc2147cd"),
                            CoverageAmount = 4000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("51f7bdf0-7f56-4754-a42c-ebce0f463854"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("5e6e573a-2f81-4df8-a0f4-b163beeda8bb"),
                            CoverageAmount = 500000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("33333333-3333-3333-3333-333333333335"),
                            IsActive = true,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("c3a35b75-5f7a-40af-bbda-a6e30407fd5a"),
                            CoverageAmount = 700000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444441"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("fcba9c4a-aecf-41fe-811d-04eb6d2bdab9"),
                            CoverageAmount = 1000000m,
                            CoveredGroup = 1,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444442"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("64735a99-6db1-4706-a372-7060f70a4115"),
                            CoverageAmount = 3000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444442"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("413d2dcc-cb9f-4845-a1b5-c705e7d285d2"),
                            CoverageAmount = 2000000m,
                            CoveredGroup = 2,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("4c8ec6ef-dfe7-4f81-bb1e-bec06e1d5f25"),
                            CoverageAmount = 5000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("f4d1e431-ac52-434f-b2a9-669df6af9a6e"),
                            CoverageAmount = 4000000m,
                            CoveredGroup = 0,
                            InsurancePlanId = new Guid("44444444-4444-4444-4444-444444444443"),
                            IsActive = true,
                            Type = 2
                        });
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillingFrequency")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CorporateClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InsurancePlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PolicyNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CorporateClientId");

                    b.HasIndex("InsurancePlanId");

                    b.ToTable("PolicyAssignments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyEndorsement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndorsementData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PremiumAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolicyAssignmentId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("PolicyEndorsements");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.AgentCustomer", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CorporateClient");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Dependent", "Dependent")
                        .WithMany()
                        .HasForeignKey("DependentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EGI_Backend.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dependent");

                    b.Navigation("Member");

                    b.Navigation("PolicyAssignment");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.ClaimDocument", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("EGI_Backend.Domain.Entities.CorporateClient", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClientDocument", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", null)
                        .WithMany("Documents")
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Dependent", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Member", "Member")
                        .WithMany("Dependents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany("Members")
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PolicyAssignment");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Payment", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "PaidByUser")
                        .WithMany()
                        .HasForeignKey("PaidBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PaidByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PlanCoverage", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.InsurancePlan", "InsurancePlan")
                        .WithMany("Coverages")
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.CorporateClient", "CorporateClient")
                        .WithMany()
                        .HasForeignKey("CorporateClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CorporateClient");

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyEndorsement", b =>
                {
                    b.HasOne("EGI_Backend.Domain.Entities.PolicyAssignment", "PolicyAssignment")
                        .WithMany()
                        .HasForeignKey("PolicyAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EGI_Backend.Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PolicyAssignment");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Claim", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.CorporateClient", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.InsurancePlan", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.Member", b =>
                {
                    b.Navigation("Dependents");
                });

            modelBuilder.Entity("EGI_Backend.Domain.Entities.PolicyAssignment", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
